EXEC SOAL1('1-1-2016','1-3-2016');
EXEC SOAL3(11);

SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE LATIHANUTS2 (
    TGLAWAL IN VARCHAR2,
    TGLAKHIR IN VARCHAR2
) AS
BEGIN
DECLARE
    CURSOR BATAS1 IS
        SELECT 
            I.PRODUCT_ID AS IDPRODUK,
            P.PRODUCT_NAME AS NAME,
            SUM(I.QUANTITY) AS JUMLAHAWAL,
            SUM(OI.QUANTITY) AS JUMLAHAKHIR,
            SUM(I.QUANTITY) - SUM(OI.QUANTITY) AS TOTAL
        FROM INVENTORIES I 
        JOIN PRODUCTS P ON P.PRODUCT_ID=I.PRODUCT_ID
        JOIN ORDER_ITEMS OI ON OI.PRODUCT_ID=I.PRODUCT_ID
        JOIN ORDERS O ON O.ORDER_ID=OI.ORDER_ID
        WHERE O.ORDER_DATE BETWEEN TO_DATE('1-1-2016', 'dd-mm-yyyy') AND TO_DATE('1-3-2016', 'dd-mm-yyyy')
        AND O.STATUS='Shipped'
        GROUP BY I.PRODUCT_ID, P.PRODUCT_NAME;
BEGIN
    DBMS_OUTPUT.PUT_LINE('KODEBRG | NAMA PROD | STOK AWAL | KELUAR | STOK AKHIR');
	DBMS_OUTPUT.PUT_LINE();
    FOR AA IN BATAS1 LOOP
		DBMS_OUTPUT.PUT_LINE(AA.IDPRODUK||' | '||AA.NAME||' | '||AA.JUMLAHAWAL||' | '||AA.JUMLAHAKHIR||' | '||AA.TOTAL);

    END LOOP;
END;
END;

EXEC LATIHANUTS2('1-1-2016', '1-3-2016');