SET SERVEROUTPUT ON;

BEGIN
    DBMS_OUTPUT.PUT_LINE(
        A => 'HELLO WORLD' /*IN VARCHAR2*/
    );
END;
SET SERVEROUTPUT ON;
DECLARE
    X NUMBER;
    Y NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE(
        A => 'HELLO WORLD' /*IN VARCHAR2*/
    );
    X:=20;
    Y:=40;
    DBMS_OUTPUT.PUT_LINE(X+Y);
END;
SET SERVEROUTPUT ON;
DECLARE
    X NUMBER;
BEGIN
    X:=87;
    CASE
        WHEN X>80 THEN
            DBMS_OUTPUT.PUT_LINE('A');
        WHEN X<65 THEN
            DBMS_OUTPUT.PUT_LINE('B');
    END CASE;
END;