SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE LATIHANUTS3 AS
BEGIN
DECLARE

    TEMP NUMBER:=0;
    JML NUMBER;
    ID NUMBER;
    CURSOR UTS IS
        SELECT
            COUNT(O.ORDER_ID) AS HITUNG,
            O.CUSTOMER_ID
        FROM ORDERS O
        GROUP BY O.CUSTOMER_ID
        ORDER BY COUNT(O.ORDER_ID) DESC;

BEGIN

    DBMS_OUTPUT.PUT_LINE('JUMLAH ORDER    |    CUSTOMER ID');
    FOR KELUARAN IN UTS LOOP
        DBMS_OUTPUT.PUT_LINE(KELUARAN.HITUNG||'        |        '||KELUARAN.CUSTOMER_ID);
    TEMP:=TEMP+1;
    IF TEMP>=10 THEN
        EXIT;
    END IF;
    END LOOP;
    
END;
END;

EXEC LATIHANUTS2;