/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package CRUD;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Invinity
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        masterMenu = new javax.swing.JMenu();
        barangMenuItem = new javax.swing.JMenuItem();
        supplierMenuItem = new javax.swing.JMenuItem();
        karyawanMenuItem = new javax.swing.JMenuItem();
        kategoriBarangMenuItem = new javax.swing.JMenuItem();
        transactionMenu = new javax.swing.JMenu();
        inventoryMenuTransaction = new javax.swing.JMenuItem();
        sellMenuItem = new javax.swing.JMenuItem();
        reportMenu = new javax.swing.JMenu();
        inventoryMenuReport = new javax.swing.JMenuItem();
        stockMenuReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        loginMenuItem.setMnemonic('o');
        loginMenuItem.setText("Login");
        fileMenu.add(loginMenuItem);

        logoutMenuItem.setMnemonic('s');
        logoutMenuItem.setText("Log out");
        fileMenu.add(logoutMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        masterMenu.setMnemonic('e');
        masterMenu.setText("Master");

        barangMenuItem.setMnemonic('t');
        barangMenuItem.setText("Barang");
        barangMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(barangMenuItem);

        supplierMenuItem.setMnemonic('y');
        supplierMenuItem.setText("Supplier");
        masterMenu.add(supplierMenuItem);

        karyawanMenuItem.setMnemonic('p');
        karyawanMenuItem.setText("Karyawan");
        masterMenu.add(karyawanMenuItem);

        kategoriBarangMenuItem.setText("Kategori Barang");
        kategoriBarangMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriBarangMenuItemActionPerformed(evt);
            }
        });
        masterMenu.add(kategoriBarangMenuItem);

        menuBar.add(masterMenu);

        transactionMenu.setMnemonic('h');
        transactionMenu.setText("Transaction");

        inventoryMenuTransaction.setMnemonic('c');
        inventoryMenuTransaction.setText("Inventory");
        transactionMenu.add(inventoryMenuTransaction);

        sellMenuItem.setMnemonic('a');
        sellMenuItem.setText("Sell");
        transactionMenu.add(sellMenuItem);

        menuBar.add(transactionMenu);

        reportMenu.setText("Report");

        inventoryMenuReport.setText("Inventory");
        inventoryMenuReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryMenuReportActionPerformed(evt);
            }
        });
        reportMenu.add(inventoryMenuReport);

        stockMenuReport.setText("Stock");
        reportMenu.add(stockMenuReport);

        menuBar.add(reportMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void barangMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangMenuItemActionPerformed
        // TODO add your handling code here:
        Product x = new Product();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        x.setAlwaysOnTop(true);
        x.setBounds(0+200,0+200,screenSize.width-400, screenSize.height-400);
        x.setVisible(true);
        x.toFront();
        x.requestFocus();
    }//GEN-LAST:event_barangMenuItemActionPerformed

    private void inventoryMenuReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryMenuReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryMenuReportActionPerformed

    private void kategoriBarangMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriBarangMenuItemActionPerformed
        // TODO add your handling code here:
        categoryProduct cp = new categoryProduct();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        cp.setAlwaysOnTop(true);
        cp.setBounds(0+200,0+200,screenSize.width-400, screenSize.height-400);
        cp.setVisible(true);
        cp.toFront();
        cp.requestFocus();
    }//GEN-LAST:event_kategoriBarangMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem barangMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem inventoryMenuReport;
    private javax.swing.JMenuItem inventoryMenuTransaction;
    private javax.swing.JMenuItem karyawanMenuItem;
    private javax.swing.JMenuItem kategoriBarangMenuItem;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenu masterMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu reportMenu;
    private javax.swing.JMenuItem sellMenuItem;
    private javax.swing.JMenuItem stockMenuReport;
    private javax.swing.JMenuItem supplierMenuItem;
    private javax.swing.JMenu transactionMenu;
    // End of variables declaration//GEN-END:variables

}
