/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUD.Master;

import CRUD.addEmployees;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Invinity
 */
public class Employees extends javax.swing.JFrame {

    public Connection conn1;
    public static ResultSet rs;

    /**
     * Creates new form Product
     */
    public Employees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tambah.setText("Add");
        tambah.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tambahComponentShown(evt);
            }
        });
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tambahComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            Class.forName("oracle.jdbc.OracleDriver");

            conn1 = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/XE", "market", "123456789");

            Statement st = conn1.createStatement();

            if (conn1 != null) {
                rs = st.executeQuery("select * from EMPLOYEES order by EMPLOYEE_ID desc ");
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("ID");
                model.addColumn("FIRST NAME");
                model.addColumn("LAST NAME");
                model.addColumn("EMAIL");
                model.addColumn("PHONE");
                model.addColumn("HIRE DATE");
                model.addColumn("MANAGER ID");
                model.addColumn("JOB");
                while (rs.next()) {
                    String id = rs.getString("EMPLOYEE_ID");
                    String firstName = rs.getString("FIRST_NAME");
                    String lastName = rs.getString("LAST_NAME");
                    String email = rs.getString("EMAIL");
                    String phone = rs.getString("PHONE");
                    String hireDate = rs.getString("HIRE_DATE");
                    String mgrID = rs.getString("MANAGER_ID");
                    String job = rs.getString("JOB_TITLE");

                    model.addRow(new Object[]{id, firstName, lastName, email, phone, hireDate, mgrID, job});
                }
                jTable1.setModel(model);

//                conn1.close();
            } else {

            }
        } catch (SQLException ex) {
//            System.out.println(ex.getMessage());
//            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentShown

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        addEmployees ae = new addEmployees();

        try {
            // TODO add your handling code here:
            Class.forName("oracle.jdbc.OracleDriver");

            conn1 = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/XE", "market", "123456789");

            Statement st = conn1.createStatement();

            if (conn1 != null) {
                String sql = "select employee_id from EMPLOYEES where employee_id = (select MAX(employee_id) from EMPLOYEES)";
                rs = st.executeQuery(sql);
                while (rs.next()) {
                    ae.empID.setText(String.valueOf(rs.getInt("employee_id")+1));
                }

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Employees.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setVisible(false);
        ae.save.setVisible(true);
        ae.update.setVisible(false);
        ae.delete.setVisible(false);
        ae.empID.disable();
        ae.setAlwaysOnTop(true);
        ae.setBounds(0 + 200, 0 + 200, 400, 600);
        ae.toFront();
        ae.requestFocus();
        ae.setVisible(true);
        ae.toFront();
        ae.requestFocus();

    }//GEN-LAST:event_tambahActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try {
            addEmployees ae = new addEmployees();

            SimpleDateFormat sdf = new SimpleDateFormat();
            sdf.applyPattern(ae.jDateChooser1.getDateFormatString());

            int baris = jTable1.getSelectedRow();
            this.setVisible(false);
            ae.setVisible(true);
            ae.setAlwaysOnTop(true);
            ae.setBounds(0 + 200, 0 + 200, 440, 600);
            ae.toFront();
            ae.requestFocus();
            if (baris != -1) {
                ae.empID.setText(jTable1.getValueAt(baris, 0).toString());
                ae.empID.disable();
                ae.firstName.setText(jTable1.getValueAt(baris, 1).toString());
                ae.lastName.setText(jTable1.getValueAt(baris, 2).toString());
                ae.email.setText(jTable1.getValueAt(baris, 3).toString());
                ae.phone.setText(jTable1.getValueAt(baris, 4).toString());
                ae.mgrID.setText(jTable1.getValueAt(baris, 6).toString());
                ae.job.setText(jTable1.getValueAt(baris, 7).toString());

                ae.jDateChooser1.setDate(sdf.parse((String) jTable1.getValueAt(baris, 5)));

                ae.save.setVisible(false);
                ae.update.setVisible(true);
                ae.delete.setVisible(true);
            }
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
//        Menu ae = new Menu();
//        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        ae.setAlwaysOnTop(true);
//        ae.setBounds(0 + 200, 0 + 200, screenSize.width - 400, screenSize.height - 400);
//        ae.toFront();
//        ae.requestFocus();
//        ae.setVisible(true);
//        ae.toFront();
//        ae.requestFocus();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
