-- SOAL PAK AGUSTINUS
-- SAYA INGIN MENAMPILKAN RATA-RATA GAJI BERDASARKAN JOB TITLE
SELECT
    JOBS.JOB_ID,
    JOBS.JOB_TITLE,
    AVG(SALARY)
FROM
    JOBS
    JOIN EMPLOYEES
    ON JOBS.JOB_ID=EMPLOYEES.JOB_ID
GROUP BY
    JOBS.JOB_ID, JOBS.JOB_TITLE;

-- TAMPILKAN NAMA DEPAN DAN NAMA BELAKANG BESERTA PASSWORD DENGAN KRITERIA PASSWORD
-- 2 KARAKTER PERTAMA DARI NAMA DEPAN
-- 3 DIGIT DARI NOMOR TELEPON DIMULAI DARI DIGIT KE 3
-- 2 KARAKTER TERAKHIR DARI NAMA BELAKANG
SELECT
    FIRST_NAME||' '||LAST_NAME AS "NAME",
    SUBSTR(LOWER(FIRST_NAME),
    1,
    2)|| SUBSTR(PHONE_NUMBER,
    5,
    2)|| SUBSTR(LAST_NAME,
    LENGTH(LAST_NAME)-1,
    2)
FROM
    EMPLOYEES;

-- NOMOR 1
-- SAYA INGIN MENAMPILKAN ID, NAMA LENGKAP, EMAIL, NO TELP, DAN GAJI KARYAWAN YANG MEMILIKI INISIAL 'D'
SELECT
    EMPLOYEE_ID                AS "EMPLOYEE ID",
    FIRST_NAME||' '||LAST_NAME AS "NAME",
    EMAIL,
    PHONE_NUMBER               AS "PHONE NUMBER",
    SALARY
FROM
    EMPLOYEES
WHERE
    FIRST_NAME LIKE 'D%';

-- NOMOR 2
-- SAYA INGIN MENCARI ID, NAMA, EMAIL, DAN NO TELP UNTUK SETIAP MANAGER
JOB_ID

FROM

JOBS

WHERE

JOB_TITLE LIKE '%Manager%';

SELECT
    EMPLOYEES.EMPLOYEE_ID                          AS "ID",
    JOBS.JOB_TITLE                                 AS JABATAN,
    EMPLOYEES.FIRST_NAME||' '||EMPLOYEES.LAST_NAME AS NAME,
    EMPLOYEES.EMAIL                                AS EMAIL,
    EMPLOYEES.PHONE_NUMBER
FROM
    EMPLOYEES
    JOIN JOBS
    ON JOBS.JOB_ID=EMPLOYEES.JOB_ID
WHERE
    JOBS.JOB_ID IN (
        SELECT
            JOB_ID
        FROM
            JOBS
        WHERE
            JOB_TITLE LIKE '%Manager%'
    );

-- NOMOR 3
-- SAYA INGIN MENCARI DATA SALES (ID, NAMA, EMAIL, NO TELP, KOMISI) BESERTA NAMA MANAGER DAN NAMA DEPARTEMEN
-- KELOMPOKKAN BERDASARKAN DEPARTEMEN DAN MANAGER
SELECT
    EMPLOYEES.EMPLOYEE_ID                          AS ID,
    EMPLOYEES.FIRST_NAME||' '||EMPLOYEES.LAST_NAME AS NAME,
    EMPLOYEES.EMAIL                                AS EMAIL,
    EMPLOYEES.PHONE_NUMBER                         AS "NO TELP",
    EMPLOYEES.COMMISSION_PCT                       AS KOMISI,
    (
    SELECT
        E.FIRST_NAME||' '||E.LAST_NAME
    FROM
        EMPLOYEES E)
    FROM
        EMPLOYEES;

SELECT
    AVG(SALARY)
FROM
    EMPLOYEES
    JOIN JOBS
    ON JOBS.JOB_ID=EMPLOYEES.JOB_ID
WHERE
    JOB_TITLE = 'Stock Manager';