-- PROCEDURE DENGAN MENGGUNAKAN USER GUDANG
-- MENAMPILKAN KETERANGAN PENGELUARAN DENGAN MENGGUNAKAN PROCEDURE
CREATE OR REPLACE PROCEDURE VPENGELUARAN (
    ID IN DETAILPENGELUARAN.KODEBRG%TYPE
) AS
BEGIN DECLARE
    KODE_KELUAR PENGELUARAN.KODEPENGELUARAN%TYPE;
    TGL PENGELUARAN.TANGGAL%TYPE;
    KET PENGELUARAN.KETERANGAN%TYPE;
    JML PENGELUARAN.JUMLAH%TYPE;
    KODEBRG DETAILPENGELUARAN.KODEBRG%TYPE;
    NMBRG BARANG.NAMA%TYPE;
    NMKAR KARYAWAN.NAMA%TYPE;
    SAT BARANG.SATUAN%TYPE;
BEGIN
    SELECT
        P.KODEPENGELUARAN, P.TANGGAL, DP.KODEBRG, B.NAMA, P.KETERANGAN, P.JUMLAH, K.NAMA, B.SATUAN
    INTO KODE_KELUAR, TGL, KODEBRG, NMBRG, KET, JML, NMKAR, SAT
    FROM
        PENGELUARAN P 
    JOIN DETAILPENGELUARAN DP ON P.KODEPENGELUARAN=DP.KODEPENGELUARAN
    JOIN BARANG B ON B.KODEBRG=DP.KODEBRG
    JOIN KARYAWAN K ON K.KODEKAR=P.KODEKAR
    WHERE
        B.KODEBRG=ID;

    DBMS_OUTPUT.PUT_LINE('PENGELUARAN');
    DBMS_OUTPUT.PUT_LINE('KODE KELUAR          TANGGAL         KODE BARANG         NAMA BARANG         KETERANGAN                  JUMLAH       KARYAWAN');
    DBMS_OUTPUT.PUT_LINE(KODE_KELUAR||'     '||TGL||'       '||KODEBRG||'       '||NMBRG||'         '||KET||'                   '||JML||' '||SAT||'  '||NMKAR);
END;
END;

-- RUN PROCEDURE DI ATAS
EXEC VPENGELUARAN('FTS0002');



-- PROCEDURE DENGAN MENGGUNAKAN USER HR
-- TAMPILKAN ID, NAMA, JABATAN, ALAMAT KANTOR
CREATE OR REPLACE PROCEDURE DETAILEMP (
    ID IN EMPLOYEES.EMPLOYEE_ID%TYPE
) AS
BEGIN DECLARE
    IDKAR EMPLOYEES.EMPLOYEE_ID%TYPE;
    NMKAR EMPLOYEES.FIRST_NAME%TYPE;
    JOB JOBS.JOB_TITLE%TYPE;
    ADDRESS LOCATIONS.STREET_ADDRESS%TYPE;
BEGIN
    SELECT
        E.EMPLOYEE_ID,
        E.FIRST_NAME||' '||E.LAST_NAME,
        J.JOB_TITLE,
        L.STREET_ADDRESS||', '||L.CITY
    INTO
        IDKAR, NMKAR, JOB, ADDRESS
    FROM EMPLOYEES E
    JOIN JOBS J ON J.JOB_ID=E.JOB_ID
    JOIN DEPARTMENTS D ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
    JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID
    WHERE
        E.EMPLOYEE_ID=ID;

    DBMS_OUTPUT.PUT_LINE('DETAIL KARYAWAN');
    DBMS_OUTPUT.PUT_LINE('ID        NAMA        JABATAN     ALAMAT');
    DBMS_OUTPUT.PUT_LINE(IDKAR||'      '||NMKAR||'      '||JOB||'       '||ADDRESS);
END;
END;

-- RUN PROCEDURE DETAILEMP
EXEC DETAILEMP(100);


-- PROCEDURE DENGAN MENGGUNAKAN PERULANGAN
CREATE OR REPLACE PROCEDURE PROCEDURELOOP (
    GAJI IN EMPLOYEES.SALARY%TYPE
) AS
BEGIN DECLARE
TOTALSALARY EMPLOYEES.SALARY%TYPE:=0;
CURSOR this IS
    SELECT
        E.EMPLOYEE_ID,
        E.FIRST_NAME,
        E.LAST_NAME,
        J.JOB_TITLE,
        L.STREET_ADDRESS,
        L.CITY,
        E.SALARY
    FROM EMPLOYEES E
    JOIN JOBS J ON J.JOB_ID=E.JOB_ID
    JOIN DEPARTMENTS D ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
    JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID
    WHERE
        E.SALARY>=GAJI;

BEGIN
    DBMS_OUTPUT.PUT_LINE('DETAIL KARYAWAN');

    FOR ULANG IN THIS
    LOOP
    DBMS_OUTPUT.PUT_LINE('ID        NAMA        JABATAN     ALAMAT      GAJI');
    DBMS_OUTPUT.PUT_LINE(ULANG.EMPLOYEE_ID||'      '||ULANG.FIRST_NAME||' '||ULANG.LAST_NAME||'      '||ULANG.JOB_TITLE||'       '||ULANG.STREET_ADDRESS||', '||ULANG.CITY||'       '||ULANG.SALARY);
    TOTALSALARY:=TOTALSALARY+ULANG.SALARY;
    END LOOP;

END;
END;

-- RUN PROCEDURE DI ATAS
EXEC PROCEDURELOOP(15000);